//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCORMResourceValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCORMResourceValidator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert_triangle_red_icon {
            get {
                object obj = ResourceManager.GetObject("alert-triangle-red_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert_triangle_redyellow_icon {
            get {
                object obj = ResourceManager.GetObject("alert-triangle-redyellow_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MetadataEditorConfiguration&gt;
        ///	&lt;sco&gt;
        ///		&lt;general name=&quot;&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot; type=&quot;container&quot;
        ///			showTag=&quot;true&quot;&gt;
        ///			&lt;identifier name=&quot;&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;10&quot;
        ///				type=&quot;container&quot; showTag=&quot;true&quot;&gt;
        ///				&lt;catalog name=&quot;&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot;
        ///					type=&quot;string:1000&quot; requiredValue=&quot;ATIA&quot; showTag=&quot;true&quot; /&gt;
        ///				&lt;entry name=&quot;&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot;
        ///					type=&quot;string:1000&quot; requiredValue=&quot;TBD&quot; showTag=&quot;true&quot; /&gt;
        ///			&lt;/identifier&gt;
        ///			&lt;title name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ui_components2004 {
            get {
                return ResourceManager.GetString("ui_components2004", resourceCulture);
            }
        }
    }
}
